language: node_js
node_js:
  - "5.10.1"
install:
  - npm install
script:
  - npm test &&
    npm run build:min
deploy:
  skip_cleanup: true
  provider: script
  script: bash scripts/deploy.sh
  on:
    all_branches: true
cache:
  directories:
    - node_modules